name: $(Major).$(Minor).$(rev:r)  # build numbering format

trigger: 
  branches:
    include: [ main ] # branch names which will trigger a build
  paths:
    include: [ Extensions/DevTestLab ] # file paths which must match to trigger a build, cannot be a variable

pr: # will trigger on PR
  branches:
    include: [ main ] # branch names which will trigger a build
  paths:
    include: [ Extensions/DevTestLab ] # file paths which must match to trigger a build, cannot be a variable

variables:
  # declared in the pipeline UI
  #  major
  #  minor
  - group:  'DevTestLab Extension'
    # this group includes the following variablea  
    #  ExtensionRoot - working folder
    #  PublisherID  - Marketplace publisher
    #  ExtensionID - Marketplace extension id
    #  vmImage - name of Azure DevOps pool to use
    #  artifactLocationName -  folder the artifact to push is stored in
    #  privateExtentionsTag - tag to show if private (else blank)
    #  taskID - Marketplace ID of task
    #  wikiFilename - name of generated docs files
stages:
  - stage: Build
    jobs:
    - job: Build
      pool: 
        vmImage: '$(vmImage)'
        demands: npm
      steps:
      # version all the task in the extension
      - task: qetza.replacetokens.replacetokens-task.replacetokens@3
        displayName: 'Setting the version for tasks in extension'
        inputs:
          rootDirectory: '$(Build.SourcesDirectory)/$(ExtensionRoot)'
          targetFiles: '**\\task.json'

      - task: TfxInstaller@3
        displayName: 'Install Tfx Tool'
        inputs:
          version: 'v0.8.x'

      - task: ms-devlabs.vsts-developer-tools-build-tasks.package-extension-build-task.PackageVSTSExtension@3
        displayName: 'Package and Publish Extension as a PROD Package '
        inputs:
          rootFolder: '$(ExtensionRoot)'
          outputPath: '$(Build.ArtifactStagingDirectory)\\$(artifactLocationName)'
          publisherId: '$(PublisherID)'
          extensionId: '$(ExtensionID)'
          extensionVersion: '$(Build.BuildNumber)'
          updateTasksVersion: true
          extensionVisibility: public

      - task: CopyFiles@2
        displayName: 'Copy Docs'
        inputs:
          SourceFolder: $(ExtensionRoot)
          Contents: |
            readme.md
            vss-extension.json
            **\task.json
          TargetFolder: '$(Build.ArtifactStagingDirectory)\\$(artifactLocationName)'

      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'vsix'
          targetPath: '$(Build.ArtifactStagingDirectory)\\$(artifactLocationName)'

  - stage: Private
    jobs:
    - deployment: Private_Deployment
      timeoutInMinutes: 0
      environment: 'Azure DevOps Marketplace (Private)'
      pool:
        vmImage: '$(vmImage)'
      strategy:
        runOnce:
          deploy:
            steps:
            # we don't need to DownloadPipelineArtifact as this is done automatically
            - template: ..\..\YAMLTemplates\publish-extension.yml
              parameters:
                 vsixPath: '$(Agent.BuildDirectory)\\$(artifactLocationName)\\$(PublisherID).$(ExtensionID)-$(Build.BuildNumber).vsix'  
                 extensionTag: '$(privateExtentionsTag)' 
                 extensionVisibility: private    

  - stage: Test
    dependsOn: Private 
    jobs:
    - deployment: Private_Test
      timeoutInMinutes: 0
      environment: 'Azure DevOps Marketplace (DevTestLabs)'
      pool:
        vmImage: '$(vmImage)'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: richardfennellBM.BM-VSTS-DevTestLab-DEV.DevTestLabsStartVm.DevTestLabsStartVm@1
              displayName: 'Start a DevTest Labs VM'
              inputs:
                ConnectedServiceName: 'RF MVP Visual Studio Enterprise (74b7c35f-1dd9-45d0-bf0c-4a8fbe3d9cb8)'
            - task: richardfennellBM.BM-VSTS-DevTestLab-DEV.DevTestLabsStopVm.DevTestLabsStopVm@1
              displayName: 'Stop a DevTest Labs VM'
              inputs:
                ConnectedServiceName: 'RF MVP Visual Studio Enterprise (74b7c35f-1dd9-45d0-bf0c-4a8fbe3d9cb8)'

  - stage: Documentation
    dependsOn: Test 
    variables:
    - group: 'WIKI Updater'
    # provides the variable
    #   gitemail - used in the Git Config
    #   gitName - used in the Git Config
    #   githubpat - used to authenticate to repo
    #   user - used to authenticate to repo
    #   repo - url of repo (without HTTPS://)
    jobs:
    - deployment: Documentation
      timeoutInMinutes: 0
      environment: 'Azure DevOps Marketplace (Documentation)'
      pool:
        vmImage: '$(vmImage)'
      strategy:
        runOnce:
          deploy:   
            steps:
              - template: ..\..\YAMLTemplates\generate-wiki-docs.yml
                parameters:
                  workingDirectory: '$(Agent.BuildDirectory)/$(artifactLocationName)'
                  wikiFilename: '$(wikiFilename)'
                  repo: '$(repo)'
                  gitname: '$(GitName)'
                  gitemail: '$(GitEmail)'
                  UserName: '$(UserName)'
                  GitHubPat: '$(GitHubPat)'

  - stage: Public
    dependsOn: Documentation
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
    - deployment: Public_Deployment
      timeoutInMinutes: 0
      environment: 'Azure DevOps Marketplace (Public)'
      pool:
        vmImage: '$(vmImage)'
      strategy:
        runOnce:
          deploy:
            steps:
              # we don't need to DownloadPipelineArtifact as this is done automatically
              - template: ..\..\YAMLTemplates\publish-extension.yml
                parameters:
                   vsixPath: '$(Agent.BuildDirectory)\\$(artifactLocationName)\\$(PublisherID).$(ExtensionID)-$(Build.BuildNumber).vsix'  
                   extensionTag: '' 
                   extensionVisibility: public    

    - job: Post_Publish
      dependsOn: Public_Deployment
      variables:
      - group: socialMedia
      pool:
        vmImage: '$(vmImage)'
      steps:
        - template: ..\..\YAMLTemplates\post-publish.yml
          parameters:
            buildNumber: $(Build.BuildNumber)
            extensionName: $(Build.DefinitionName)
            socialmediaLogicAppURL: $(socialmediaLogicAppURL)